# TCL File Generated by Component Editor 20.1
# Sat May 09 04:41:57 PKT 2026
# DO NOT MODIFY


# 
# cpu_top "cpu_top" v1.0
# Akbar Shah Zar 2026.05.09.04:41:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cpu_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME cpu_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME cpu_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CPUtop
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cputop.v VERILOG PATH cputop.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL CPUtop
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cputop.v VERILOG PATH cputop.v


# 
# parameters
# 
add_parameter STATE_IDLE STD_LOGIC_VECTOR 0
set_parameter_property STATE_IDLE DEFAULT_VALUE 0
set_parameter_property STATE_IDLE DISPLAY_NAME STATE_IDLE
set_parameter_property STATE_IDLE WIDTH 4
set_parameter_property STATE_IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_IDLE UNITS None
set_parameter_property STATE_IDLE ALLOWED_RANGES 0:15
set_parameter_property STATE_IDLE HDL_PARAMETER true
add_parameter STATE_IF STD_LOGIC_VECTOR 1
set_parameter_property STATE_IF DEFAULT_VALUE 1
set_parameter_property STATE_IF DISPLAY_NAME STATE_IF
set_parameter_property STATE_IF WIDTH 4
set_parameter_property STATE_IF TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_IF UNITS None
set_parameter_property STATE_IF ALLOWED_RANGES 0:15
set_parameter_property STATE_IF HDL_PARAMETER true
add_parameter STATE_ID STD_LOGIC_VECTOR 2
set_parameter_property STATE_ID DEFAULT_VALUE 2
set_parameter_property STATE_ID DISPLAY_NAME STATE_ID
set_parameter_property STATE_ID WIDTH 4
set_parameter_property STATE_ID TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_ID UNITS None
set_parameter_property STATE_ID ALLOWED_RANGES 0:15
set_parameter_property STATE_ID HDL_PARAMETER true
add_parameter STATE_EX STD_LOGIC_VECTOR 3
set_parameter_property STATE_EX DEFAULT_VALUE 3
set_parameter_property STATE_EX DISPLAY_NAME STATE_EX
set_parameter_property STATE_EX WIDTH 4
set_parameter_property STATE_EX TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_EX UNITS None
set_parameter_property STATE_EX ALLOWED_RANGES 0:15
set_parameter_property STATE_EX HDL_PARAMETER true
add_parameter STATE_MEM STD_LOGIC_VECTOR 4
set_parameter_property STATE_MEM DEFAULT_VALUE 4
set_parameter_property STATE_MEM DISPLAY_NAME STATE_MEM
set_parameter_property STATE_MEM WIDTH 4
set_parameter_property STATE_MEM TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_MEM UNITS None
set_parameter_property STATE_MEM ALLOWED_RANGES 0:15
set_parameter_property STATE_MEM HDL_PARAMETER true
add_parameter STATE_WB STD_LOGIC_VECTOR 5
set_parameter_property STATE_WB DEFAULT_VALUE 5
set_parameter_property STATE_WB DISPLAY_NAME STATE_WB
set_parameter_property STATE_WB WIDTH 4
set_parameter_property STATE_WB TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_WB UNITS None
set_parameter_property STATE_WB ALLOWED_RANGES 0:15
set_parameter_property STATE_WB HDL_PARAMETER true
add_parameter STATE_HALT STD_LOGIC_VECTOR 6
set_parameter_property STATE_HALT DEFAULT_VALUE 6
set_parameter_property STATE_HALT DISPLAY_NAME STATE_HALT
set_parameter_property STATE_HALT WIDTH 4
set_parameter_property STATE_HALT TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_HALT UNITS None
set_parameter_property STATE_HALT ALLOWED_RANGES 0:15
set_parameter_property STATE_HALT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point data_in
# 
add_interface data_in conduit end
set_interface_property data_in associatedClock clock
set_interface_property data_in associatedReset ""
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in data_in data Input 16


# 
# connection point instruction_in
# 
add_interface instruction_in conduit end
set_interface_property instruction_in associatedClock clock
set_interface_property instruction_in associatedReset ""
set_interface_property instruction_in ENABLED true
set_interface_property instruction_in EXPORT_OF ""
set_interface_property instruction_in PORT_NAME_MAP ""
set_interface_property instruction_in CMSIS_SVD_VARIABLES ""
set_interface_property instruction_in SVD_ADDRESS_GROUP ""

add_interface_port instruction_in instruction_in instruction_signal Input 18


# 
# connection point instruction_addr_out
# 
add_interface instruction_addr_out conduit end
set_interface_property instruction_addr_out associatedClock clock
set_interface_property instruction_addr_out associatedReset ""
set_interface_property instruction_addr_out ENABLED true
set_interface_property instruction_addr_out EXPORT_OF ""
set_interface_property instruction_addr_out PORT_NAME_MAP ""
set_interface_property instruction_addr_out CMSIS_SVD_VARIABLES ""
set_interface_property instruction_addr_out SVD_ADDRESS_GROUP ""

add_interface_port instruction_addr_out instruction_address addr_sig Output 10


# 
# connection point data_address
# 
add_interface data_address conduit end
set_interface_property data_address associatedClock clock
set_interface_property data_address associatedReset ""
set_interface_property data_address ENABLED true
set_interface_property data_address EXPORT_OF ""
set_interface_property data_address PORT_NAME_MAP ""
set_interface_property data_address CMSIS_SVD_VARIABLES ""
set_interface_property data_address SVD_ADDRESS_GROUP ""

add_interface_port data_address data_address data_addr Output 10


# 
# connection point done_in
# 
add_interface done_in conduit end
set_interface_property done_in associatedClock clock
set_interface_property done_in associatedReset ""
set_interface_property done_in ENABLED true
set_interface_property done_in EXPORT_OF ""
set_interface_property done_in PORT_NAME_MAP ""
set_interface_property done_in CMSIS_SVD_VARIABLES ""
set_interface_property done_in SVD_ADDRESS_GROUP ""

add_interface_port done_in done done_sig Output 1


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset ""
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_out data Output 16


# 
# connection point h_regs
# 
add_interface h_regs conduit end
set_interface_property h_regs associatedClock clock
set_interface_property h_regs associatedReset ""
set_interface_property h_regs ENABLED true
set_interface_property h_regs EXPORT_OF ""
set_interface_property h_regs PORT_NAME_MAP ""
set_interface_property h_regs CMSIS_SVD_VARIABLES ""
set_interface_property h_regs SVD_ADDRESS_GROUP ""

add_interface_port h_regs h0 h0_sig Output 16
add_interface_port h_regs h1 h1_sig Output 16
add_interface_port h_regs h2 h2_sig Output 16
add_interface_port h_regs h3 h3_sig Output 16


# 
# connection point data_read_enable
# 
add_interface data_read_enable conduit end
set_interface_property data_read_enable associatedClock clock
set_interface_property data_read_enable associatedReset ""
set_interface_property data_read_enable ENABLED true
set_interface_property data_read_enable EXPORT_OF ""
set_interface_property data_read_enable PORT_NAME_MAP ""
set_interface_property data_read_enable CMSIS_SVD_VARIABLES ""
set_interface_property data_read_enable SVD_ADDRESS_GROUP ""

add_interface_port data_read_enable data_R read_enable Output 1


# 
# connection point data_write_enable
# 
add_interface data_write_enable conduit end
set_interface_property data_write_enable associatedClock clock
set_interface_property data_write_enable associatedReset ""
set_interface_property data_write_enable ENABLED true
set_interface_property data_write_enable EXPORT_OF ""
set_interface_property data_write_enable PORT_NAME_MAP ""
set_interface_property data_write_enable CMSIS_SVD_VARIABLES ""
set_interface_property data_write_enable SVD_ADDRESS_GROUP ""

add_interface_port data_write_enable data_W write_enable Output 1

