# TCL File Generated by Component Editor 20.1
# Sat May 09 05:40:18 PKT 2026
# DO NOT MODIFY


# 
# cpu_debug_tap "cpu_debug_tap" v1.0
# Akbar Shah Zar 2026.05.09.05:40:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cpu_debug_tap
# 
set_module_property DESCRIPTION ""
set_module_property NAME cpu_debug_tap
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME cpu_debug_tap
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cpu_debug_tap
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cpu_debug_tap.v VERILOG PATH cpu_debug_tap.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 1
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 s0_address address Input 4
add_interface_port s0 s0_read read Input 1
add_interface_port s0 s0_write write Input 1
add_interface_port s0 s0_byteenable byteenable Input 4
add_interface_port s0 s0_burstcount burstcount Input 8
add_interface_port s0 s0_beginbursttransfer beginbursttransfer Input 1
add_interface_port s0 s0_writedata writedata Input 32
add_interface_port s0 s0_readdata readdata Output 32
add_interface_port s0 s0_readdatavalid readdatavalid Output 1
add_interface_port s0 s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point instruction_address
# 
add_interface instruction_address conduit end
set_interface_property instruction_address associatedClock clock
set_interface_property instruction_address associatedReset ""
set_interface_property instruction_address ENABLED true
set_interface_property instruction_address EXPORT_OF ""
set_interface_property instruction_address PORT_NAME_MAP ""
set_interface_property instruction_address CMSIS_SVD_VARIABLES ""
set_interface_property instruction_address SVD_ADDRESS_GROUP ""

add_interface_port instruction_address instruction_address addr_sig Input 10


# 
# connection point instruction_in
# 
add_interface instruction_in conduit end
set_interface_property instruction_in associatedClock clock
set_interface_property instruction_in associatedReset ""
set_interface_property instruction_in ENABLED true
set_interface_property instruction_in EXPORT_OF ""
set_interface_property instruction_in PORT_NAME_MAP ""
set_interface_property instruction_in CMSIS_SVD_VARIABLES ""
set_interface_property instruction_in SVD_ADDRESS_GROUP ""

add_interface_port instruction_in instruction_in instruction_signal Input 18


# 
# connection point data_address
# 
add_interface data_address conduit end
set_interface_property data_address associatedClock clock
set_interface_property data_address associatedReset ""
set_interface_property data_address ENABLED true
set_interface_property data_address EXPORT_OF ""
set_interface_property data_address PORT_NAME_MAP ""
set_interface_property data_address CMSIS_SVD_VARIABLES ""
set_interface_property data_address SVD_ADDRESS_GROUP ""

add_interface_port data_address data_address data_addr Input 10


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset ""
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_out data Input 16


# 
# connection point done_in
# 
add_interface done_in conduit end
set_interface_property done_in associatedClock clock
set_interface_property done_in associatedReset ""
set_interface_property done_in ENABLED true
set_interface_property done_in EXPORT_OF ""
set_interface_property done_in PORT_NAME_MAP ""
set_interface_property done_in CMSIS_SVD_VARIABLES ""
set_interface_property done_in SVD_ADDRESS_GROUP ""

add_interface_port done_in done done Input 1


# 
# connection point data_R_en
# 
add_interface data_R_en conduit end
set_interface_property data_R_en associatedClock clock
set_interface_property data_R_en associatedReset ""
set_interface_property data_R_en ENABLED true
set_interface_property data_R_en EXPORT_OF ""
set_interface_property data_R_en PORT_NAME_MAP ""
set_interface_property data_R_en CMSIS_SVD_VARIABLES ""
set_interface_property data_R_en SVD_ADDRESS_GROUP ""

add_interface_port data_R_en data_R read_enable Input 1


# 
# connection point data_W_en
# 
add_interface data_W_en conduit end
set_interface_property data_W_en associatedClock clock
set_interface_property data_W_en associatedReset ""
set_interface_property data_W_en ENABLED true
set_interface_property data_W_en EXPORT_OF ""
set_interface_property data_W_en PORT_NAME_MAP ""
set_interface_property data_W_en CMSIS_SVD_VARIABLES ""
set_interface_property data_W_en SVD_ADDRESS_GROUP ""

add_interface_port data_W_en data_W data_w_sig Input 1


# 
# connection point h_regs
# 
add_interface h_regs conduit end
set_interface_property h_regs associatedClock clock
set_interface_property h_regs associatedReset ""
set_interface_property h_regs ENABLED true
set_interface_property h_regs EXPORT_OF ""
set_interface_property h_regs PORT_NAME_MAP ""
set_interface_property h_regs CMSIS_SVD_VARIABLES ""
set_interface_property h_regs SVD_ADDRESS_GROUP ""

add_interface_port h_regs h0 h0_sig Input 16
add_interface_port h_regs h1 h1_sig Input 16
add_interface_port h_regs h2 h2_sig Input 16
add_interface_port h_regs h3 h3_sig Input 16

