# TCL File Generated by Component Editor 20.1
# Fri May 08 19:22:15 PKT 2026
# DO NOT MODIFY


# 
# cpu_top "cpu_top" v1.0
# Akbar Shah Zar 2026.05.08.19:22:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cpu_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME cpu_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME cpu_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CPUtop
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cputop.v VERILOG PATH cputop.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL CPUtop
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cputop.v VERILOG PATH cputop.v


# 
# parameters
# 
add_parameter STATE_IDLE STD_LOGIC_VECTOR 0
set_parameter_property STATE_IDLE DEFAULT_VALUE 0
set_parameter_property STATE_IDLE DISPLAY_NAME STATE_IDLE
set_parameter_property STATE_IDLE WIDTH 4
set_parameter_property STATE_IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_IDLE UNITS None
set_parameter_property STATE_IDLE ALLOWED_RANGES 0:15
set_parameter_property STATE_IDLE HDL_PARAMETER true
add_parameter STATE_IF STD_LOGIC_VECTOR 1
set_parameter_property STATE_IF DEFAULT_VALUE 1
set_parameter_property STATE_IF DISPLAY_NAME STATE_IF
set_parameter_property STATE_IF WIDTH 4
set_parameter_property STATE_IF TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_IF UNITS None
set_parameter_property STATE_IF ALLOWED_RANGES 0:15
set_parameter_property STATE_IF HDL_PARAMETER true
add_parameter STATE_ID STD_LOGIC_VECTOR 2
set_parameter_property STATE_ID DEFAULT_VALUE 2
set_parameter_property STATE_ID DISPLAY_NAME STATE_ID
set_parameter_property STATE_ID WIDTH 4
set_parameter_property STATE_ID TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_ID UNITS None
set_parameter_property STATE_ID ALLOWED_RANGES 0:15
set_parameter_property STATE_ID HDL_PARAMETER true
add_parameter STATE_EX STD_LOGIC_VECTOR 3
set_parameter_property STATE_EX DEFAULT_VALUE 3
set_parameter_property STATE_EX DISPLAY_NAME STATE_EX
set_parameter_property STATE_EX WIDTH 4
set_parameter_property STATE_EX TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_EX UNITS None
set_parameter_property STATE_EX ALLOWED_RANGES 0:15
set_parameter_property STATE_EX HDL_PARAMETER true
add_parameter STATE_MEM STD_LOGIC_VECTOR 4
set_parameter_property STATE_MEM DEFAULT_VALUE 4
set_parameter_property STATE_MEM DISPLAY_NAME STATE_MEM
set_parameter_property STATE_MEM WIDTH 4
set_parameter_property STATE_MEM TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_MEM UNITS None
set_parameter_property STATE_MEM ALLOWED_RANGES 0:15
set_parameter_property STATE_MEM HDL_PARAMETER true
add_parameter STATE_WB STD_LOGIC_VECTOR 5
set_parameter_property STATE_WB DEFAULT_VALUE 5
set_parameter_property STATE_WB DISPLAY_NAME STATE_WB
set_parameter_property STATE_WB WIDTH 4
set_parameter_property STATE_WB TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_WB UNITS None
set_parameter_property STATE_WB ALLOWED_RANGES 0:15
set_parameter_property STATE_WB HDL_PARAMETER true
add_parameter STATE_HALT STD_LOGIC_VECTOR 6
set_parameter_property STATE_HALT DEFAULT_VALUE 6
set_parameter_property STATE_HALT DISPLAY_NAME STATE_HALT
set_parameter_property STATE_HALT WIDTH 4
set_parameter_property STATE_HALT TYPE STD_LOGIC_VECTOR
set_parameter_property STATE_HALT UNITS None
set_parameter_property STATE_HALT ALLOWED_RANGES 0:15
set_parameter_property STATE_HALT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point cpu_top
# 
add_interface cpu_top nios_custom_instruction end
set_interface_property cpu_top clockCycle 0
set_interface_property cpu_top operands 2
set_interface_property cpu_top ENABLED true
set_interface_property cpu_top EXPORT_OF ""
set_interface_property cpu_top PORT_NAME_MAP ""
set_interface_property cpu_top CMSIS_SVD_VARIABLES ""
set_interface_property cpu_top SVD_ADDRESS_GROUP ""

add_interface_port cpu_top cpu_top_a a Input 5
add_interface_port cpu_top cpu_top_c c Input 5
add_interface_port cpu_top cpu_top_b b Input 5
add_interface_port cpu_top cpu_top_clk clk Input 1
add_interface_port cpu_top cpu_top_clk_en clk_en Input 1
add_interface_port cpu_top cpu_top_dataa dataa Input 32
add_interface_port cpu_top cpu_top_datab datab Input 32
add_interface_port cpu_top cpu_top_done done Output 1
add_interface_port cpu_top cpu_top_n n Input 2
add_interface_port cpu_top cpu_top_readra readra Input 1
add_interface_port cpu_top cpu_top_readrb readrb Input 1
add_interface_port cpu_top cpu_top_reset reset Input 1
add_interface_port cpu_top cpu_top_reset_req reset_req Input 1
add_interface_port cpu_top cpu_top_result result Output 32
add_interface_port cpu_top cpu_top_start start Input 1
add_interface_port cpu_top cpu_top_writerc writerc Input 1

