# TCL File Generated by Component Editor 20.1
# Sat May 09 05:39:51 PKT 2026
# DO NOT MODIFY


# 
# cpu_signal_fanout "cpu_signal_fanout" v1.0
# Akbar Shah Zar 2026.05.09.05:39:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cpu_signal_fanout
# 
set_module_property DESCRIPTION ""
set_module_property NAME cpu_signal_fanout
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME cpu_signal_fanout
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cpu_signal_fanout
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cpu_signal_fanout.v VERILOG PATH rtl/cpu_signal_fanout.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point cpu_instruction_address_in
# 
add_interface cpu_instruction_address_in conduit end
set_interface_property cpu_instruction_address_in associatedClock clock
set_interface_property cpu_instruction_address_in associatedReset ""
set_interface_property cpu_instruction_address_in ENABLED true
set_interface_property cpu_instruction_address_in EXPORT_OF ""
set_interface_property cpu_instruction_address_in PORT_NAME_MAP ""
set_interface_property cpu_instruction_address_in CMSIS_SVD_VARIABLES ""
set_interface_property cpu_instruction_address_in SVD_ADDRESS_GROUP ""

add_interface_port cpu_instruction_address_in cpu_instruction_address addr_sig Input 10


# 
# connection point cpu_data_address_in
# 
add_interface cpu_data_address_in conduit end
set_interface_property cpu_data_address_in associatedClock clock
set_interface_property cpu_data_address_in associatedReset ""
set_interface_property cpu_data_address_in ENABLED true
set_interface_property cpu_data_address_in EXPORT_OF ""
set_interface_property cpu_data_address_in PORT_NAME_MAP ""
set_interface_property cpu_data_address_in CMSIS_SVD_VARIABLES ""
set_interface_property cpu_data_address_in SVD_ADDRESS_GROUP ""

add_interface_port cpu_data_address_in cpu_data_address data_addr Input 10


# 
# connection point cpu_data_out_in
# 
add_interface cpu_data_out_in conduit end
set_interface_property cpu_data_out_in associatedClock clock
set_interface_property cpu_data_out_in associatedReset ""
set_interface_property cpu_data_out_in ENABLED true
set_interface_property cpu_data_out_in EXPORT_OF ""
set_interface_property cpu_data_out_in PORT_NAME_MAP ""
set_interface_property cpu_data_out_in CMSIS_SVD_VARIABLES ""
set_interface_property cpu_data_out_in SVD_ADDRESS_GROUP ""

add_interface_port cpu_data_out_in cpu_data_out data Input 16


# 
# connection point cpu_data_R_in
# 
add_interface cpu_data_R_in conduit end
set_interface_property cpu_data_R_in associatedClock clock
set_interface_property cpu_data_R_in associatedReset ""
set_interface_property cpu_data_R_in ENABLED true
set_interface_property cpu_data_R_in EXPORT_OF ""
set_interface_property cpu_data_R_in PORT_NAME_MAP ""
set_interface_property cpu_data_R_in CMSIS_SVD_VARIABLES ""
set_interface_property cpu_data_R_in SVD_ADDRESS_GROUP ""

add_interface_port cpu_data_R_in cpu_data_R read_enable Input 1


# 
# connection point cpu_data_W_in
# 
add_interface cpu_data_W_in conduit end
set_interface_property cpu_data_W_in associatedClock clock
set_interface_property cpu_data_W_in associatedReset ""
set_interface_property cpu_data_W_in ENABLED true
set_interface_property cpu_data_W_in EXPORT_OF ""
set_interface_property cpu_data_W_in PORT_NAME_MAP ""
set_interface_property cpu_data_W_in CMSIS_SVD_VARIABLES ""
set_interface_property cpu_data_W_in SVD_ADDRESS_GROUP ""

add_interface_port cpu_data_W_in cpu_data_W write_enable Input 1


# 
# connection point cpu_done_in
# 
add_interface cpu_done_in conduit end
set_interface_property cpu_done_in associatedClock clock
set_interface_property cpu_done_in associatedReset ""
set_interface_property cpu_done_in ENABLED true
set_interface_property cpu_done_in EXPORT_OF ""
set_interface_property cpu_done_in PORT_NAME_MAP ""
set_interface_property cpu_done_in CMSIS_SVD_VARIABLES ""
set_interface_property cpu_done_in SVD_ADDRESS_GROUP ""

add_interface_port cpu_done_in cpu_done done_sig Input 1


# 
# connection point instr_mem_addr_out
# 
add_interface instr_mem_addr_out conduit end
set_interface_property instr_mem_addr_out associatedClock clock
set_interface_property instr_mem_addr_out associatedReset ""
set_interface_property instr_mem_addr_out ENABLED true
set_interface_property instr_mem_addr_out EXPORT_OF ""
set_interface_property instr_mem_addr_out PORT_NAME_MAP ""
set_interface_property instr_mem_addr_out CMSIS_SVD_VARIABLES ""
set_interface_property instr_mem_addr_out SVD_ADDRESS_GROUP ""

add_interface_port instr_mem_addr_out instr_mem_addr addr_sig Output 10


# 
# connection point data_mem_addr_out
# 
add_interface data_mem_addr_out conduit end
set_interface_property data_mem_addr_out associatedClock clock
set_interface_property data_mem_addr_out associatedReset ""
set_interface_property data_mem_addr_out ENABLED true
set_interface_property data_mem_addr_out EXPORT_OF ""
set_interface_property data_mem_addr_out PORT_NAME_MAP ""
set_interface_property data_mem_addr_out CMSIS_SVD_VARIABLES ""
set_interface_property data_mem_addr_out SVD_ADDRESS_GROUP ""

add_interface_port data_mem_addr_out data_mem_addr data_addr Output 10


# 
# connection point data_mem_data_in_out
# 
add_interface data_mem_data_in_out conduit end
set_interface_property data_mem_data_in_out associatedClock clock
set_interface_property data_mem_data_in_out associatedReset ""
set_interface_property data_mem_data_in_out ENABLED true
set_interface_property data_mem_data_in_out EXPORT_OF ""
set_interface_property data_mem_data_in_out PORT_NAME_MAP ""
set_interface_property data_mem_data_in_out CMSIS_SVD_VARIABLES ""
set_interface_property data_mem_data_in_out SVD_ADDRESS_GROUP ""

add_interface_port data_mem_data_in_out data_mem_data_in data Output 16


# 
# connection point data_mem_read_en_out
# 
add_interface data_mem_read_en_out conduit end
set_interface_property data_mem_read_en_out associatedClock clock
set_interface_property data_mem_read_en_out associatedReset ""
set_interface_property data_mem_read_en_out ENABLED true
set_interface_property data_mem_read_en_out EXPORT_OF ""
set_interface_property data_mem_read_en_out PORT_NAME_MAP ""
set_interface_property data_mem_read_en_out CMSIS_SVD_VARIABLES ""
set_interface_property data_mem_read_en_out SVD_ADDRESS_GROUP ""

add_interface_port data_mem_read_en_out data_mem_read_en read_enable Output 1


# 
# connection point data_mem_write_en_out
# 
add_interface data_mem_write_en_out conduit end
set_interface_property data_mem_write_en_out associatedClock clock
set_interface_property data_mem_write_en_out associatedReset ""
set_interface_property data_mem_write_en_out ENABLED true
set_interface_property data_mem_write_en_out EXPORT_OF ""
set_interface_property data_mem_write_en_out PORT_NAME_MAP ""
set_interface_property data_mem_write_en_out CMSIS_SVD_VARIABLES ""
set_interface_property data_mem_write_en_out SVD_ADDRESS_GROUP ""

add_interface_port data_mem_write_en_out data_mem_write_en write_enable Output 1


# 
# connection point dbg_instruction_address_out
# 
add_interface dbg_instruction_address_out conduit end
set_interface_property dbg_instruction_address_out associatedClock clock
set_interface_property dbg_instruction_address_out associatedReset ""
set_interface_property dbg_instruction_address_out ENABLED true
set_interface_property dbg_instruction_address_out EXPORT_OF ""
set_interface_property dbg_instruction_address_out PORT_NAME_MAP ""
set_interface_property dbg_instruction_address_out CMSIS_SVD_VARIABLES ""
set_interface_property dbg_instruction_address_out SVD_ADDRESS_GROUP ""

add_interface_port dbg_instruction_address_out dbg_instruction_address addr_sig Output 10


# 
# connection point dbg_data_address_out
# 
add_interface dbg_data_address_out conduit end
set_interface_property dbg_data_address_out associatedClock clock
set_interface_property dbg_data_address_out associatedReset ""
set_interface_property dbg_data_address_out ENABLED true
set_interface_property dbg_data_address_out EXPORT_OF ""
set_interface_property dbg_data_address_out PORT_NAME_MAP ""
set_interface_property dbg_data_address_out CMSIS_SVD_VARIABLES ""
set_interface_property dbg_data_address_out SVD_ADDRESS_GROUP ""

add_interface_port dbg_data_address_out dbg_data_address data_addr Output 10


# 
# connection point dbg_data_out_out
# 
add_interface dbg_data_out_out conduit end
set_interface_property dbg_data_out_out associatedClock clock
set_interface_property dbg_data_out_out associatedReset ""
set_interface_property dbg_data_out_out ENABLED true
set_interface_property dbg_data_out_out EXPORT_OF ""
set_interface_property dbg_data_out_out PORT_NAME_MAP ""
set_interface_property dbg_data_out_out CMSIS_SVD_VARIABLES ""
set_interface_property dbg_data_out_out SVD_ADDRESS_GROUP ""

add_interface_port dbg_data_out_out dbg_data_out data Output 16


# 
# connection point dbg_data_R_out
# 
add_interface dbg_data_R_out conduit end
set_interface_property dbg_data_R_out associatedClock clock
set_interface_property dbg_data_R_out associatedReset ""
set_interface_property dbg_data_R_out ENABLED true
set_interface_property dbg_data_R_out EXPORT_OF ""
set_interface_property dbg_data_R_out PORT_NAME_MAP ""
set_interface_property dbg_data_R_out CMSIS_SVD_VARIABLES ""
set_interface_property dbg_data_R_out SVD_ADDRESS_GROUP ""

add_interface_port dbg_data_R_out dbg_data_R read_enable Output 1


# 
# connection point dbg_data_W_out
# 
add_interface dbg_data_W_out conduit end
set_interface_property dbg_data_W_out associatedClock clock
set_interface_property dbg_data_W_out associatedReset ""
set_interface_property dbg_data_W_out ENABLED true
set_interface_property dbg_data_W_out EXPORT_OF ""
set_interface_property dbg_data_W_out PORT_NAME_MAP ""
set_interface_property dbg_data_W_out CMSIS_SVD_VARIABLES ""
set_interface_property dbg_data_W_out SVD_ADDRESS_GROUP ""

add_interface_port dbg_data_W_out dbg_data_W data_w_sig Output 1


# 
# connection point dbg_done_out
# 
add_interface dbg_done_out conduit end
set_interface_property dbg_done_out associatedClock clock
set_interface_property dbg_done_out associatedReset ""
set_interface_property dbg_done_out ENABLED true
set_interface_property dbg_done_out EXPORT_OF ""
set_interface_property dbg_done_out PORT_NAME_MAP ""
set_interface_property dbg_done_out CMSIS_SVD_VARIABLES ""
set_interface_property dbg_done_out SVD_ADDRESS_GROUP ""

add_interface_port dbg_done_out dbg_done done Output 1

