# TCL File Generated by Component Editor 20.1
# Sat May 09 04:43:42 PKT 2026
# DO NOT MODIFY


# 
# data_memory "data_memory" v1.0
# Akbar Shah Zar 2026.05.09.04:43:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module data_memory
# 
set_module_property DESCRIPTION ""
set_module_property NAME data_memory
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME data_memory
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DataMemory
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DataMemory.v VERILOG PATH rtl/DataMemory.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point read_enable
# 
add_interface read_enable conduit end
set_interface_property read_enable associatedClock clock
set_interface_property read_enable associatedReset ""
set_interface_property read_enable ENABLED true
set_interface_property read_enable EXPORT_OF ""
set_interface_property read_enable PORT_NAME_MAP ""
set_interface_property read_enable CMSIS_SVD_VARIABLES ""
set_interface_property read_enable SVD_ADDRESS_GROUP ""

add_interface_port read_enable re read_enable Input 1


# 
# connection point write_enable
# 
add_interface write_enable conduit end
set_interface_property write_enable associatedClock clock
set_interface_property write_enable associatedReset ""
set_interface_property write_enable ENABLED true
set_interface_property write_enable EXPORT_OF ""
set_interface_property write_enable PORT_NAME_MAP ""
set_interface_property write_enable CMSIS_SVD_VARIABLES ""
set_interface_property write_enable SVD_ADDRESS_GROUP ""

add_interface_port write_enable we write_enable Input 1


# 
# connection point address_in
# 
add_interface address_in conduit end
set_interface_property address_in associatedClock clock
set_interface_property address_in associatedReset ""
set_interface_property address_in ENABLED true
set_interface_property address_in EXPORT_OF ""
set_interface_property address_in PORT_NAME_MAP ""
set_interface_property address_in CMSIS_SVD_VARIABLES ""
set_interface_property address_in SVD_ADDRESS_GROUP ""

add_interface_port address_in addr data_addr Input 10


# 
# connection point data_in
# 
add_interface data_in conduit end
set_interface_property data_in associatedClock clock
set_interface_property data_in associatedReset ""
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in din data Input 16


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset ""
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out dout data Output 16

