# TCL File Generated by Component Editor 20.1
# Sat May 09 04:10:21 PKT 2026
# DO NOT MODIFY


# 
# instruction_memory "instruction_memory" v1.0
# Akbar Shah Zar 2026.05.09.04:10:21
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module instruction_memory
# 
set_module_property DESCRIPTION ""
set_module_property NAME instruction_memory
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME instruction_memory
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL InstructionMemory
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file InstructionMemory.v VERILOG PATH rtl/InstructionMemory.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point instruction_out
# 
add_interface instruction_out conduit end
set_interface_property instruction_out associatedClock "clock"
set_interface_property instruction_out associatedReset ""
set_interface_property instruction_out ENABLED true
set_interface_property instruction_out EXPORT_OF ""
set_interface_property instruction_out PORT_NAME_MAP ""
set_interface_property instruction_out CMSIS_SVD_VARIABLES ""
set_interface_property instruction_out SVD_ADDRESS_GROUP ""

add_interface_port instruction_out instruction instruction_signal Output 18


# 
# connection point addr_in
# 
add_interface addr_in conduit end
set_interface_property addr_in associatedClock "clock"
set_interface_property addr_in associatedReset ""
set_interface_property addr_in ENABLED true
set_interface_property addr_in EXPORT_OF ""
set_interface_property addr_in PORT_NAME_MAP ""
set_interface_property addr_in CMSIS_SVD_VARIABLES ""
set_interface_property addr_in SVD_ADDRESS_GROUP ""

add_interface_port addr_in addr addr_sig Input 10

