# TCL File Generated by Component Editor 20.1
# Sat May 09 05:30:00 PKT 2026
# DO NOT MODIFY


# 
# instruction_fanout "instruction_fanout" v1.0
# Akbar Shah Zar 2026.05.09.05:30:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module instruction_fanout
# 
set_module_property DESCRIPTION ""
set_module_property NAME instruction_fanout
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Akbar Shah Zar"
set_module_property DISPLAY_NAME instruction_fanout
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL instruction_fanout
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file instruction_fanout.v VERILOG PATH rtl/instruction_fanout.v TOP_LEVEL_FILE


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point instruction_in
# 
add_interface instruction_in conduit end
set_interface_property instruction_in associatedClock clock
set_interface_property instruction_in associatedReset ""
set_interface_property instruction_in ENABLED true
set_interface_property instruction_in EXPORT_OF ""
set_interface_property instruction_in PORT_NAME_MAP ""
set_interface_property instruction_in CMSIS_SVD_VARIABLES ""
set_interface_property instruction_in SVD_ADDRESS_GROUP ""

add_interface_port instruction_in instr_in instruction_signal Input 18


# 
# connection point instruction_to_cpu
# 
add_interface instruction_to_cpu conduit end
set_interface_property instruction_to_cpu associatedClock clock
set_interface_property instruction_to_cpu associatedReset ""
set_interface_property instruction_to_cpu ENABLED true
set_interface_property instruction_to_cpu EXPORT_OF ""
set_interface_property instruction_to_cpu PORT_NAME_MAP ""
set_interface_property instruction_to_cpu CMSIS_SVD_VARIABLES ""
set_interface_property instruction_to_cpu SVD_ADDRESS_GROUP ""

add_interface_port instruction_to_cpu instr_to_cpu instruction_signal Output 18


# 
# connection point instruction_to_dbg
# 
add_interface instruction_to_dbg conduit end
set_interface_property instruction_to_dbg associatedClock clock
set_interface_property instruction_to_dbg associatedReset ""
set_interface_property instruction_to_dbg ENABLED true
set_interface_property instruction_to_dbg EXPORT_OF ""
set_interface_property instruction_to_dbg PORT_NAME_MAP ""
set_interface_property instruction_to_dbg CMSIS_SVD_VARIABLES ""
set_interface_property instruction_to_dbg SVD_ADDRESS_GROUP ""

add_interface_port instruction_to_dbg instr_to_dbg instruction_signal Output 18
