// simd_system.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module simd_system (
		input  wire  clk_clk,       //   clk.clk
		input  wire  reset_reset_n  // reset.reset_n
	);

	wire  [31:0] master_0_master_readdata;                                // mm_interconnect_0:master_0_master_readdata -> master_0:master_readdata
	wire         master_0_master_waitrequest;                             // mm_interconnect_0:master_0_master_waitrequest -> master_0:master_waitrequest
	wire  [31:0] master_0_master_address;                                 // master_0:master_address -> mm_interconnect_0:master_0_master_address
	wire         master_0_master_read;                                    // master_0:master_read -> mm_interconnect_0:master_0_master_read
	wire   [3:0] master_0_master_byteenable;                              // master_0:master_byteenable -> mm_interconnect_0:master_0_master_byteenable
	wire         master_0_master_readdatavalid;                           // mm_interconnect_0:master_0_master_readdatavalid -> master_0:master_readdatavalid
	wire         master_0_master_write;                                   // master_0:master_write -> mm_interconnect_0:master_0_master_write
	wire  [31:0] master_0_master_writedata;                               // master_0:master_writedata -> mm_interconnect_0:master_0_master_writedata
	wire         mm_interconnect_0_cpu_debug_tap_0_s0_beginbursttransfer; // mm_interconnect_0:cpu_debug_tap_0_s0_beginbursttransfer -> cpu_debug_tap_0:s0_beginbursttransfer
	wire  [31:0] mm_interconnect_0_cpu_debug_tap_0_s0_readdata;           // cpu_debug_tap_0:s0_readdata -> mm_interconnect_0:cpu_debug_tap_0_s0_readdata
	wire         mm_interconnect_0_cpu_debug_tap_0_s0_waitrequest;        // cpu_debug_tap_0:s0_waitrequest -> mm_interconnect_0:cpu_debug_tap_0_s0_waitrequest
	wire   [1:0] mm_interconnect_0_cpu_debug_tap_0_s0_address;            // mm_interconnect_0:cpu_debug_tap_0_s0_address -> cpu_debug_tap_0:s0_address
	wire         mm_interconnect_0_cpu_debug_tap_0_s0_read;               // mm_interconnect_0:cpu_debug_tap_0_s0_read -> cpu_debug_tap_0:s0_read
	wire   [3:0] mm_interconnect_0_cpu_debug_tap_0_s0_byteenable;         // mm_interconnect_0:cpu_debug_tap_0_s0_byteenable -> cpu_debug_tap_0:s0_byteenable
	wire         mm_interconnect_0_cpu_debug_tap_0_s0_readdatavalid;      // cpu_debug_tap_0:s0_readdatavalid -> mm_interconnect_0:cpu_debug_tap_0_s0_readdatavalid
	wire   [7:0] mm_interconnect_0_cpu_debug_tap_0_s0_burstcount;         // mm_interconnect_0:cpu_debug_tap_0_s0_burstcount -> cpu_debug_tap_0:s0_burstcount
	wire         rst_controller_reset_out_reset;                          // rst_controller:reset_out -> [cpu_debug_tap_0:reset_n, mm_interconnect_0:cpu_debug_tap_0_reset_reset_bridge_in_reset_reset, mm_interconnect_0:master_0_clk_reset_reset_bridge_in_reset_reset]

	cpu_debug_tap cpu_debug_tap_0 (
		.clk                   (clk_clk),                                                 // clock.clk
		.reset_n               (~rst_controller_reset_out_reset),                         // reset.reset_n
		.s0_address            (mm_interconnect_0_cpu_debug_tap_0_s0_address),            //    s0.address
		.s0_read               (mm_interconnect_0_cpu_debug_tap_0_s0_read),               //      .read
		.s0_byteenable         (mm_interconnect_0_cpu_debug_tap_0_s0_byteenable),         //      .byteenable
		.s0_burstcount         (mm_interconnect_0_cpu_debug_tap_0_s0_burstcount),         //      .burstcount
		.s0_beginbursttransfer (mm_interconnect_0_cpu_debug_tap_0_s0_beginbursttransfer), //      .beginbursttransfer
		.s0_readdata           (mm_interconnect_0_cpu_debug_tap_0_s0_readdata),           //      .readdata
		.s0_readdatavalid      (mm_interconnect_0_cpu_debug_tap_0_s0_readdatavalid),      //      .readdatavalid
		.s0_waitrequest        (mm_interconnect_0_cpu_debug_tap_0_s0_waitrequest)         //      .waitrequest
	);

	CPUtop #(
		.STATE_IDLE (4'b0000),
		.STATE_IF   (4'b0001),
		.STATE_ID   (4'b0010),
		.STATE_EX   (4'b0011),
		.STATE_MEM  (4'b0100),
		.STATE_WB   (4'b0101),
		.STATE_HALT (4'b0110)
	) cpu_top_0 (
		.clk               (clk_clk), //   clock.clk
		.cpu_top_a         (),        // cpu_top.a
		.cpu_top_c         (),        //        .c
		.cpu_top_b         (),        //        .b
		.cpu_top_clk       (),        //        .clk
		.cpu_top_clk_en    (),        //        .clk_en
		.cpu_top_dataa     (),        //        .dataa
		.cpu_top_datab     (),        //        .datab
		.cpu_top_done      (),        //        .done
		.cpu_top_n         (),        //        .n
		.cpu_top_readra    (),        //        .readra
		.cpu_top_readrb    (),        //        .readrb
		.cpu_top_reset     (),        //        .reset
		.cpu_top_reset_req (),        //        .reset_req
		.cpu_top_result    (),        //        .result
		.cpu_top_start     (),        //        .start
		.cpu_top_writerc   ()         //        .writerc
	);

	simd_system_master_0 #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) master_0 (
		.clk_clk              (clk_clk),                       //          clk.clk
		.clk_reset_reset      (~reset_reset_n),                //    clk_reset.reset
		.master_address       (master_0_master_address),       //       master.address
		.master_readdata      (master_0_master_readdata),      //             .readdata
		.master_read          (master_0_master_read),          //             .read
		.master_write         (master_0_master_write),         //             .write
		.master_writedata     (master_0_master_writedata),     //             .writedata
		.master_waitrequest   (master_0_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (master_0_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (master_0_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                               // master_reset.reset
	);

	simd_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                     (clk_clk),                                                 //                                   clk_0_clk.clk
		.cpu_debug_tap_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                          // cpu_debug_tap_0_reset_reset_bridge_in_reset.reset
		.master_0_clk_reset_reset_bridge_in_reset_reset    (rst_controller_reset_out_reset),                          //    master_0_clk_reset_reset_bridge_in_reset.reset
		.master_0_master_address                           (master_0_master_address),                                 //                             master_0_master.address
		.master_0_master_waitrequest                       (master_0_master_waitrequest),                             //                                            .waitrequest
		.master_0_master_byteenable                        (master_0_master_byteenable),                              //                                            .byteenable
		.master_0_master_read                              (master_0_master_read),                                    //                                            .read
		.master_0_master_readdata                          (master_0_master_readdata),                                //                                            .readdata
		.master_0_master_readdatavalid                     (master_0_master_readdatavalid),                           //                                            .readdatavalid
		.master_0_master_write                             (master_0_master_write),                                   //                                            .write
		.master_0_master_writedata                         (master_0_master_writedata),                               //                                            .writedata
		.cpu_debug_tap_0_s0_address                        (mm_interconnect_0_cpu_debug_tap_0_s0_address),            //                          cpu_debug_tap_0_s0.address
		.cpu_debug_tap_0_s0_read                           (mm_interconnect_0_cpu_debug_tap_0_s0_read),               //                                            .read
		.cpu_debug_tap_0_s0_readdata                       (mm_interconnect_0_cpu_debug_tap_0_s0_readdata),           //                                            .readdata
		.cpu_debug_tap_0_s0_beginbursttransfer             (mm_interconnect_0_cpu_debug_tap_0_s0_beginbursttransfer), //                                            .beginbursttransfer
		.cpu_debug_tap_0_s0_burstcount                     (mm_interconnect_0_cpu_debug_tap_0_s0_burstcount),         //                                            .burstcount
		.cpu_debug_tap_0_s0_byteenable                     (mm_interconnect_0_cpu_debug_tap_0_s0_byteenable),         //                                            .byteenable
		.cpu_debug_tap_0_s0_readdatavalid                  (mm_interconnect_0_cpu_debug_tap_0_s0_readdatavalid),      //                                            .readdatavalid
		.cpu_debug_tap_0_s0_waitrequest                    (mm_interconnect_0_cpu_debug_tap_0_s0_waitrequest)         //                                            .waitrequest
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
